export interface LegalSection {
  heading: string;
  body: string[];
  list?: string[];
}

export interface LegalDoc {
  slug: string;
  title: string;
  subtitle: string;
  effectiveDate: string;
  sections: LegalSection[];
}

const EFFECTIVE = "April 24, 2026";

export const legalDocs: Record<string, LegalDoc> = {
  privacy: {
    slug: "privacy",
    title: "Privacy policy",
    subtitle:
      "How we collect, use, and protect personal information when you use telecaller.ai and our managed AI-telecalling services.",
    effectiveDate: EFFECTIVE,
    sections: [
      {
        heading: "1. Who we are",
        body: [
          "telecaller.ai is operated from Hyderabad, India. References to \"we,\" \"us,\" or \"our\" mean the entity operating telecaller.ai. References to \"you\" mean the business or individual using our website or services.",
          "For questions about this policy, email abhinav@telecaller.ai or call +91 90001 30400.",
        ],
      },
      {
        heading: "2. Information we collect",
        body: [
          "We collect only what is necessary to deliver and improve our services:",
        ],
        list: [
          "Business contact details you provide when booking a demo, signing up, or contacting us (name, email, phone, company, role).",
          "Call metadata and recordings generated by our AI agents on your behalf (call time, duration, transcript, outcome, caller phone number).",
          "Account and billing information (payment identifiers, GSTIN, invoices).",
          "Technical logs from our website and platform (IP address, device/browser type, pages visited, timestamps) for security and analytics.",
        ],
      },
      {
        heading: "3. How we use information",
        body: ["We use the information we collect to:"],
        list: [
          "Deliver the AI-telecalling services you have contracted.",
          "Handle billing, support, onboarding, and customer communication.",
          "Improve model performance, voice quality, and compliance tooling.",
          "Meet legal and regulatory obligations under Indian law, including TRAI, DLT, and DPDP requirements.",
          "Detect fraud, abuse, or security incidents.",
        ],
      },
      {
        heading: "4. Data fiduciary and processor roles",
        body: [
          "When you use telecaller.ai to call your own leads or customers, you act as the Data Fiduciary under the DPDP Act, 2023. We act as a Data Processor on your behalf, strictly within the scope of your instructions and our Data Processing Agreement (DPA).",
          "For information we collect directly about you as our client (account, billing, support), we act as the Data Fiduciary.",
        ],
      },
      {
        heading: "5. Where data is stored",
        body: [
          "Call recordings, transcripts, and lead data are stored on infrastructure located in India. We do not transfer personal data outside India except where necessary to provide the service and permitted by applicable law, in which case equivalent safeguards are in place.",
        ],
      },
      {
        heading: "6. Who we share data with",
        body: ["We share personal data only with:"],
        list: [
          "Subprocessors required to deliver the service (telephony carriers, cloud hosting, voice synthesis providers), each bound by confidentiality and DPDP-aligned contractual terms.",
          "Regulatory or law-enforcement authorities where required by Indian law.",
          "Professional advisors (legal, accounting, auditors) under confidentiality obligations.",
        ],
      },
      {
        heading: "7. Retention",
        body: [
          "We retain call recordings and transcripts for the retention period specified in your service plan (30 / 90 / 365 days). Lead data is retained for the duration of your contract and for up to 12 months thereafter for audit and regulatory purposes, unless you request earlier deletion.",
          "Billing and tax records are retained for the period required by Indian tax law (currently 8 years).",
        ],
      },
      {
        heading: "8. Your rights under the DPDP Act",
        body: [
          "Indian residents have the right to access, correct, and erase their personal data, to withdraw consent, and to nominate a representative. To exercise any of these rights, email abhinav@telecaller.ai with the subject line \"DPDP request.\" We respond within 30 days.",
          "If you are not satisfied with our response, you may approach the Data Protection Board of India.",
        ],
      },
      {
        heading: "9. Security",
        body: [
          "We protect personal data with encryption in transit (TLS) and at rest (AES-256), role-based access controls, audit logging, and regular security reviews. No method of transmission or storage is perfectly secure; we will notify affected parties and the Data Protection Board of significant breaches as required by law.",
        ],
      },
      {
        heading: "10. Cookies and analytics",
        body: [
          "Our website uses minimal essential cookies for session handling and, where applicable, privacy-preserving analytics to understand aggregate usage. We do not sell website data to advertisers.",
        ],
      },
      {
        heading: "11. Children",
        body: [
          "Our services are not directed at individuals under 18. We do not knowingly collect data from children.",
        ],
      },
      {
        heading: "12. Changes to this policy",
        body: [
          "We may update this policy from time to time. Material changes will be communicated by email to active clients and posted on this page with an updated effective date.",
        ],
      },
      {
        heading: "13. Contact",
        body: [
          "Grievance Officer and Data Protection Contact:",
          "Abhinav, Founder · abhinav@telecaller.ai · +91 90001 30400 · Hyderabad, India.",
        ],
      },
    ],
  },

  terms: {
    slug: "terms",
    title: "Terms of service",
    subtitle:
      "The agreement that governs your use of telecaller.ai and our managed AI-telecalling services.",
    effectiveDate: EFFECTIVE,
    sections: [
      {
        heading: "1. Agreement",
        body: [
          "These Terms of Service (\"Terms\") form a binding agreement between you (\"Client,\" \"you\") and the entity operating telecaller.ai (\"we,\" \"us\"). By signing a service order, using our platform, or completing onboarding, you agree to these Terms and any attached Data Processing Agreement (DPA).",
        ],
      },
      {
        heading: "2. Services",
        body: [
          "We provide managed AI-telecalling services as described on telecaller.ai and in your service order. This typically includes agent design, voice deployment, compliance configuration, CRM integration, reporting, and ongoing optimization.",
          "Services are delivered as a managed service. You are not licensing self-serve software.",
        ],
      },
      {
        heading: "3. Your responsibilities",
        body: ["You agree to:"],
        list: [
          "Use our services only to contact leads for whom you have a valid, recent consent basis (typically inquiries in the last 48 hours).",
          "Not upload or instruct us to call cold databases, scraped lists, or purchased contacts.",
          "Provide accurate business information for DLT registration and compliance.",
          "Maintain your own lawful basis for any personal data you direct us to process.",
          "Pay invoices on time and maintain a valid GST registration if applicable.",
        ],
      },
      {
        heading: "4. Our responsibilities",
        body: ["We agree to:"],
        list: [
          "Deliver services with reasonable care and skill.",
          "Maintain TRAI, DLT, DND, and DPDP-aligned operational controls at the platform level.",
          "Keep your data confidential and process it only on your instructions as Data Processor.",
          "Provide monthly reports and respond to support within the SLA for your plan.",
        ],
      },
      {
        heading: "5. Fees and billing",
        body: [
          "Fees are as stated in your service order. Invoices are issued monthly in advance and are due within 7 days of issue. Overage charges (per-minute fees beyond plan limits) are billed in arrears.",
          "All fees are exclusive of GST, which will be added to invoices as applicable under Indian tax law.",
          "Late payments accrue interest at 1.5% per month or the maximum permitted by law, whichever is lower.",
        ],
      },
      {
        heading: "6. Term and termination",
        body: [
          "Initial term is 3 months from the service start date. After the initial term, the agreement continues on a month-to-month basis and may be terminated by either party with 30 days' written notice.",
          "We may suspend or terminate services immediately if you breach Section 3 (Your responsibilities), fail to pay after a 15-day cure period, or if required by law.",
          "On termination, we will export your call recordings, transcripts, and lead data to you in a standard format and delete our copies within 30 days, retaining only records required by law.",
        ],
      },
      {
        heading: "7. Warranties and disclaimers",
        body: [
          "We warrant that we will perform services with reasonable care and skill and in compliance with applicable Indian law at the platform level.",
          "To the maximum extent permitted by law, we disclaim all other warranties, express or implied, including warranties of merchantability, fitness for a particular purpose, and non-infringement. AI outputs are probabilistic and may contain errors; you are responsible for reviewing material outputs before acting on them.",
        ],
      },
      {
        heading: "8. Limitation of liability",
        body: [
          "To the maximum extent permitted by law, each party's aggregate liability under this agreement in any 12-month period is limited to the fees paid by you to us in that period.",
          "Neither party is liable for indirect, incidental, consequential, or loss-of-profit damages.",
          "Nothing in this clause limits liability for fraud, gross negligence, or liability that cannot lawfully be limited.",
        ],
      },
      {
        heading: "9. Confidentiality",
        body: [
          "Each party will protect the other's confidential information with at least the same care it uses for its own and will use it only for the purposes of this agreement.",
        ],
      },
      {
        heading: "10. Indemnification",
        body: [
          "You agree to indemnify us against third-party claims arising from (a) your breach of Section 3, (b) your use of our services to contact non-consented contacts, or (c) content or instructions you provide that infringe third-party rights.",
          "We agree to indemnify you against third-party claims that our platform infringes a third party's intellectual property, subject to the Limitation of Liability above.",
        ],
      },
      {
        heading: "11. Force majeure",
        body: [
          "Neither party is liable for failure to perform due to causes beyond its reasonable control, including internet outages, telecom-carrier disruptions, regulatory orders, natural disasters, or acts of state.",
        ],
      },
      {
        heading: "12. Governing law and disputes",
        body: [
          "These Terms are governed by the laws of India. Disputes will be subject to the exclusive jurisdiction of the courts at Hyderabad, Telangana.",
          "Parties will first attempt good-faith resolution through the nominated contacts before escalating.",
        ],
      },
      {
        heading: "13. Contact",
        body: [
          "Notices and contract questions: abhinav@telecaller.ai · +91 90001 30400 · Hyderabad, India.",
        ],
      },
    ],
  },

  dpdp: {
    slug: "dpdp",
    title: "DPDP compliance",
    subtitle:
      "How telecaller.ai complies with the Digital Personal Data Protection Act, 2023 and related Indian regulation.",
    effectiveDate: EFFECTIVE,
    sections: [
      {
        heading: "1. Our role under the DPDP Act, 2023",
        body: [
          "Under the Digital Personal Data Protection Act, 2023 (\"DPDP Act\"), telecaller.ai acts primarily as a Data Processor on behalf of our clients (who are Data Fiduciaries for the leads and customers they call using our platform).",
          "For personal data we collect directly from our clients and website visitors (account, billing, support interactions), we act as Data Fiduciary and are accountable under the DPDP Act accordingly.",
        ],
      },
      {
        heading: "2. Lawful basis for processing",
        body: [
          "We process personal data only on the following bases:",
        ],
        list: [
          "Consent captured by our client from the data principal (for calls made to leads).",
          "Performance of our contract with our client.",
          "Compliance with legal obligations under Indian law (TRAI, DLT, taxation).",
          "Legitimate business interests that do not override the data principal's rights (e.g. fraud prevention, service security).",
        ],
      },
      {
        heading: "3. Data minimization",
        body: [
          "We collect and process the minimum data necessary to deliver the service. Call recordings are limited to the business interaction, and personal data fields captured are scoped to what the client configures for qualification.",
        ],
      },
      {
        heading: "4. Cross-border transfers",
        body: [
          "Our primary storage is in India. Where a subprocessor outside India is required to deliver part of the service (for example, a voice-model provider), transfers are made only to jurisdictions not restricted by the Central Government and under contractual safeguards equivalent to DPDP standards.",
        ],
      },
      {
        heading: "5. Data principal rights",
        body: [
          "We operationally support data principal requests to access, correct, update, and erase personal data, to withdraw consent, and to nominate a representative. As Data Processor, we execute such requests through our client (the Data Fiduciary) within 7 working days of receiving the instruction.",
          "Direct requests from data principals relating to data we hold as Data Fiduciary can be sent to abhinav@telecaller.ai.",
        ],
      },
      {
        heading: "6. Security safeguards",
        body: [
          "We maintain the following safeguards, aligned with DPDP standards and ISO 27001 principles:",
        ],
        list: [
          "Encryption in transit (TLS 1.2+) and at rest (AES-256) for call recordings, transcripts, and lead data.",
          "Role-based access with least privilege; MFA enforced for all administrative access.",
          "Comprehensive audit logging of data access and administrative actions.",
          "Regular vulnerability scanning and annual third-party penetration testing.",
          "Documented incident-response runbooks and breach-notification procedures.",
          "Vendor due-diligence and DPAs with every subprocessor that handles personal data.",
        ],
      },
      {
        heading: "7. Breach notification",
        body: [
          "In the event of a personal data breach, we will notify affected clients without undue delay and, where required, the Data Protection Board of India and affected data principals in accordance with the DPDP Act and associated rules.",
        ],
      },
      {
        heading: "8. Retention and deletion",
        body: [
          "Retention periods are set per the client's service plan (typically 30 / 90 / 365 days for recordings). Deletion is irreversible at the end of the retention window. Clients may request shorter retention in their service order.",
        ],
      },
      {
        heading: "9. Consent and TRAI compliance",
        body: [
          "We only dial numbers for which the client has a valid consent basis (typically an inquiry in the last 48 hours). We scrub against the DND registry before every outbound call and route all campaigns through DLT-registered templates.",
          "Our AI agents disclose their AI nature in the opening line of every call, in the caller's language.",
        ],
      },
      {
        heading: "10. Data Processing Agreement",
        body: [
          "Every client signs our Data Processing Agreement (DPA) at onboarding. The DPA formalizes the roles, instructions, subprocessors, security measures, breach-notification timelines, and audit rights.",
          "Request a copy of the DPA template by emailing abhinav@telecaller.ai.",
        ],
      },
      {
        heading: "11. Grievance redressal",
        body: [
          "Grievance Officer: Abhinav, Founder.",
          "Email: abhinav@telecaller.ai · Phone: +91 90001 30400 · Hyderabad, India.",
          "Grievances are acknowledged within 2 working days and resolved within 30 days in line with DPDP requirements.",
        ],
      },
    ],
  },

  refund: {
    slug: "refund",
    title: "Refund policy",
    subtitle:
      "When and how telecaller.ai offers refunds, credits, and pilot exits.",
    effectiveDate: EFFECTIVE,
    sections: [
      {
        heading: "1. 7-day free pilot",
        body: [
          "New clients are eligible for a 7-day free pilot on their first 100 inbound inquiries. No credit card or commitment is required to start the pilot. If we do not outperform your current team on qualified leads per 100 inquiries, you walk away owing nothing.",
          "Pilot eligibility is confirmed in writing before setup begins.",
        ],
      },
      {
        heading: "2. Paid subscriptions",
        body: [
          "All paid plans have a 3-month minimum term from the service start date. Subscriptions are billed monthly in advance and are non-refundable once the month has started, except as set out below.",
        ],
      },
      {
        heading: "3. When we will issue a refund or credit",
        body: ["We will issue a pro-rated refund or service credit in the following cases:"],
        list: [
          "If we fail to deliver the service for more than 72 continuous hours due to a fault on our side, we credit the affected days to your next invoice.",
          "If a billing error results in a duplicate or incorrect charge, we refund the incorrect amount within 7 working days of acknowledging the error.",
          "If we terminate the agreement for reasons unrelated to your breach, we refund any prepaid fees for service not yet delivered.",
        ],
      },
      {
        heading: "4. Setup fees",
        body: [
          "The onboarding setup fee covers agent design, DLT registration, script engineering, and deployment. Once setup has begun it is non-refundable, regardless of whether you choose to proceed to a paid subscription.",
          "We waive the setup fee for most clients in their first 90 days; where waived, nothing further applies.",
        ],
      },
      {
        heading: "5. Overage charges",
        body: [
          "Minutes consumed beyond your plan's included minutes are billed in arrears at your plan's overage rate and are non-refundable once consumed. We alert clients at 80% of their plan minutes each month so you can choose whether to upgrade or cap spending.",
        ],
      },
      {
        heading: "6. Annual plans",
        body: [
          "Annual upfront subscriptions receive a 15% discount. If you cancel before the end of an annual term for reasons other than our material breach, the discount is recovered at standard monthly rates from the amount paid, and any remaining balance is refunded. We do not charge an early-cancellation penalty.",
        ],
      },
      {
        heading: "7. After the minimum term",
        body: [
          "After the 3-month initial term, you may cancel with 30 days' written notice. Service continues until the end of the notice period and is paid through that date. No refund is issued for the notice period.",
        ],
      },
      {
        heading: "8. How to request a refund",
        body: [
          "Email abhinav@telecaller.ai with the subject line \"Refund request\" and your account details. We acknowledge requests within 2 working days and resolve them within 15 working days.",
          "Approved refunds are returned to the original payment method. If that is not possible, we issue a bank transfer to an account in your registered business name.",
        ],
      },
      {
        heading: "9. Not covered by this policy",
        body: [
          "This policy does not cover third-party fees (for example, telecom-carrier pass-through charges, payment-gateway fees, or GST), which are refunded only to the extent they are themselves refundable.",
        ],
      },
      {
        heading: "10. Contact",
        body: [
          "For refund and billing questions: abhinav@telecaller.ai · +91 90001 30400 · Hyderabad, India.",
        ],
      },
    ],
  },
};
